"""HMAC webhook tests via TestClient.

Signing mirrors `mock_payment_provider.sign`: HMAC-SHA256 hex over the exact
raw JSON bytes with the secret read from `.env` (`WEBHOOK_SECRET`). The router
verifies the seal on `await request.body()` *before* parsing JSON, so tests
POST raw `content=` bytes, not `json=` (which would not let us control the
exact signed bytes).
"""

from datetime import date, timedelta

import pytest

from app.domains.bookings.models import BookingStatus
from app.domains.payments.service import WebhookAuthError, verify_signature
from tests import helpers

URL = "/api/v1/webhooks/payment"


def _processing_booking() -> dict:
    """PROCESSING booking on room 201 backed by an active hold (pay scenario)."""
    check_in = date.today() + timedelta(days=7)
    check_out = date.today() + timedelta(days=9)
    helpers.create_hold(201, helpers.GUEST_1)
    created = helpers.create_booking(
        helpers.GUEST_1, 201, check_in, check_out, BookingStatus.PROCESSING, 130000.0
    )
    assert created["ref"], "bookings.ref should be generated by the DB"
    return created


def _post(client, raw: bytes, sig: str | None):
    headers = {"Content-Type": "application/json"}
    if sig is not None:
        headers["X-Signature"] = sig
    return client.post(URL, content=raw, headers=headers)


def test_valid_event_confirms_booking(client):
    created = _processing_booking()
    event = helpers.make_event(event_id="evt_valid_001", reference=created["ref"], amount=created["total"])
    raw = helpers.encode_event(event)
    resp = _post(client, raw, helpers.sign_raw(raw))
    assert resp.status_code == 200, resp.text
    assert resp.json() == {"status": "confirmed"}
    assert helpers.get_booking_status(created["booking_id"]) == "confirmed"
    assert helpers.count("payments", f"WHERE booking_id = {created['booking_id']}") == 1
    assert helpers.count("processed_events", "WHERE event_id = 'evt_valid_001'") == 1
    assert helpers.count("room_nights", f"WHERE booking_id = {created['booking_id']}") == 2
    assert helpers.count("holds", "WHERE room_id = 201") == 0


def test_duplicate_retry_is_idempotent(client):
    created = _processing_booking()
    event = helpers.make_event(event_id="evt_dup_001", reference=created["ref"], amount=created["total"])
    raw = helpers.encode_event(event)
    sig = helpers.sign_raw(raw)
    assert _post(client, raw, sig).json() == {"status": "confirmed"}
    resp = _post(client, raw, sig)
    assert resp.status_code == 200, resp.text
    assert resp.json() == {"status": "duplicate"}
    assert helpers.count("payments", f"WHERE booking_id = {created['booking_id']}") == 1


def test_wrong_signature_returns_401_and_writes_nothing(client):
    created = _processing_booking()
    event = helpers.make_event(event_id="evt_bad_001", reference=created["ref"], amount=created["total"])
    raw = helpers.encode_event(event)
    resp = _post(client, raw, "deadbeef" * 8)
    assert resp.status_code == 401, resp.text
    assert helpers.count("processed_events", "WHERE event_id = 'evt_bad_001'") == 0
    assert helpers.get_booking_status(created["booking_id"]) == "processing"


def test_missing_signature_returns_401(client):
    created = _processing_booking()
    event = helpers.make_event(event_id="evt_nosig_001", reference=created["ref"], amount=created["total"])
    raw = helpers.encode_event(event)
    assert _post(client, raw, None).status_code == 401


def test_tampered_body_fails_signature(client):
    created = _processing_booking()
    event = helpers.make_event(event_id="evt_tamper_001", reference=created["ref"], amount=created["total"])
    raw = helpers.encode_event(event)
    sig = helpers.sign_raw(raw)
    tampered = helpers.encode_event({**event, "amount": created["total"] + 5000})
    resp = _post(client, tampered, sig)
    assert resp.status_code == 401, resp.text


def test_amount_mismatch_returns_422_and_keeps_processing(client):
    created = _processing_booking()
    event = helpers.make_event(event_id="evt_amt_001", reference=created["ref"], amount=created["total"] + 1000)
    raw = helpers.encode_event(event)
    resp = _post(client, raw, helpers.sign_raw(raw))
    assert resp.status_code == 422, resp.text
    assert helpers.get_booking_status(created["booking_id"]) == "processing"
    assert helpers.count("payments", f"WHERE booking_id = {created['booking_id']}") == 0


def test_unknown_reference_returns_orphan(client):
    event = helpers.make_event(event_id="evt_orphan_001", reference="REF-DOES-NOT-EXIST", amount=1000)
    raw = helpers.encode_event(event)
    resp = _post(client, raw, helpers.sign_raw(raw))
    assert resp.status_code == 200, resp.text
    assert resp.json() == {"status": "orphan"}
    assert helpers.count("processed_events", "WHERE event_id = 'evt_orphan_001'") == 1


def test_non_succeeded_type_is_ignored(client):
    created = _processing_booking()
    event = helpers.make_event(
        event_id="evt_ignored_001", reference=created["ref"],
        amount=created["total"], event_type="payment.failed",
    )
    raw = helpers.encode_event(event)
    resp = _post(client, raw, helpers.sign_raw(raw))
    assert resp.status_code == 200, resp.text
    assert resp.json() == {"status": "ignored"}
    assert helpers.get_booking_status(created["booking_id"]) == "processing"


def test_invalid_json_with_valid_signature_returns_422(client):
    raw = b"{not-json"
    resp = _post(client, raw, helpers.sign_raw(raw))
    assert resp.status_code == 422, resp.text


def test_verify_signature_unit():
    secret = helpers.webhook_secret()
    raw = b'{"a":1}'
    verify_signature(raw, helpers.sign_raw(raw, secret))  # must not raise
    with pytest.raises(WebhookAuthError):
        verify_signature(raw, "wrong")
    with pytest.raises(WebhookAuthError):
        verify_signature(raw, "")
