"""

Revision ID: 67472fc9e912
Revises: f544d03a5ec7
Create Date: 2026-09-22 11:23:09.258044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '67472fc9e912'
down_revision: Union[str, Sequence[str], None] = 'f544d03a5ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('ref', sa.String(length=32), sa.Computed("'BOOK-' || booking_id", persisted=True), nullable=True))
    op.create_index(op.f('ix_bookings_ref'), 'bookings', ['ref'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_ref'), table_name='bookings')
    op.drop_column('bookings', 'ref')
    # ### end Alembic commands ###
