"""add rooms room_state

Revision ID: 746006cfbe5d
Revises: ab0a64cf0363
Create Date: 2026-09-22 11:49:59.181651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '746006cfbe5d'
down_revision: Union[str, Sequence[str], None] = 'ab0a64cf0363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('room_state', sa.Enum('CLEAN', 'DIRTY', name='roomstate'), server_default='CLEAN', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'room_state')
    # ### end Alembic commands ###
